# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: build project

on:
  release:
  push:
  pull_request:
    branches: master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup GraalVM 
    - uses: DeLaGuardo/setup-graalvm@master
      with:
          graalvm-version: '20.3.0.java11' 
          
    - name: Build with Maven
      run: mvn package -Pnative
